[package]
name = "emoji-alfredworkflow"
version = "2.0.0"
authors = ["Alpha Chen <alpha.chen@gmail.com>"]

[dependencies]
failure = "*"
rayon = "*"
reqwest = "*"
select = "*"
serde = "1.0"
serde_derive = "*"
serde_json = "*"
